print('Calculo de hora trabalhada!')
hv = float(input('Quanto vale sua hora de trabalho: '))
ht = int(input('Quantas horas voce trabalha por mes: '))
print(end='\n\n')
print(f'+Salário Bruto: \t R${(hv * ht):.2f}')
print(f'-Imposto de Renda(11%):\t R${((hv * ht) * 0.11):.2f}')
print(f'-INSS(8%):\t\t R${((hv * ht) * 0.08):.2f}')
print(f'-Sindicato(5%):\t\t R${((hv * ht) * 0.05):.2f}')
print(f'=Salário Liquido:\t R${(((hv * ht) - (((hv * ht) * 0.11) + ((hv * ht) * 0.08) + ((hv * ht) * 0.05)))):.2f}')